

export const AnagramGameData = [
  {
    id: 1,
    letters: ["Y", "D", "A", "M", "Z", "E"], // Rearranged from "MAZE"
    validWords: [
      "MAZE",
      "DAZE",
      "MADE",
      "DAME",
      "YEAM",
      "MAZY",
      "MEAD",
      "AMAZE",
      "ZED",
      "DAY",
      "MAD",
      "YAM",
      "DAM",
      "MAY",
      "DEY",
      "AYE",
    ],
  },
  {
    id: 2,
    letters: ["R", "P", "A", "T", "S", "O"], // Rearranged from "STOP"
    validWords: [
      "STOP",
      "TOPS",
      "POTS",
      "SPOT",
      "OPTS",
      "POST",
      "TAPS",
      "STAR",
      "TRAP",
      "PART",
      "TAR",
      "RAT",
      "POT",
      "TOP",
      "SOP",
      "OPT",
      "PAT",
      "SAT",
      "ART",
    ],
  },
  {
    id: 3,
    letters: ["N", "L", "E", "K", "C", "I"], // Rearranged from "LICK"
    validWords: [
      "LICK",
      "NICK",
      "LINK",
      "LINE",
      "NICE",
      "KINE",
      "LIEN",
      "NECK",
      "CLICK",
      "KIN",
      "NIL",
      "INK",
      "ELK",
      "LEK",
      "ICE",
    ],
  },
  {
    id: 4,
    letters: ["G", "B", "U", "F", "O", "A"], // Rearranged from "BUFF"
    validWords: [
      "GOAF",
      "GOOF",
      "GAFF",
      "BUFF",
      "BUFO",
      "FOGA",
      "BOG",
      "FUG",
      "FAB",
      "FOG",
      "BAG",
      "BUG",
      "OAF",
    ],
  },
  {
    id: 5,
    letters: ["I", "S", "T", "E", "W", "H"], // Rearranged from "WHET"
    validWords: [
      "WISH",
      "WIST",
      "WHET",
      "WITS",
      "WEST",
      "WITE",
      "WHIT",
      "THIS",
      "THEW",
      "TIES",
      "SITE",
      "SET",
      "HIT",
      "WET",
      "SIT",
      "HIS",
      "TIE",
    ],
  },
  {
    id: 6,
    letters: ["A", "D", "R", "N", "V", "U"], // Rearranged from "RAND"
    validWords: [
      "RAND",
      "RUND",
      "RUAN",
      "DURN",
      "DURA",
      "URNA",
      "NARD",
      "VAND",
      "VAN",
      "RUN",
      "AND",
      "DUN",
      "URN",
    ],
  },
  {
    id: 7,
    letters: ["M", "L", "Y", "J", "O", "E"], // Rearranged from "JOY"
    validWords: [
      "MOLY",
      "MOLE",
      "MOJO",
      "JOEY",
      "JOLE",
      "YOME",
      "YLEM",
      "LYME",
      "JOY",
      "JOE",
      "YOM",
      "JEM",
      "ELM",
    ],
  },
  {
    id: 8,
    letters: ["C", "K", "Q", "U", "S", "I"], // Rearranged from "QUICK"
    validWords: [
      "QUICK",
      "QUICKS",
      "QUIS",
      "SICK",
      "SUCK",
      "ICK",
      "CIS",
      "SKI",
      "KIS",
      "QUA",
      "SUK",
    ],
  },
  {
    id: 9,
    letters: ["P", "X", "N", "O", "E", "A"], // Rearranged from "PEON"
    validWords: [
      "PEON",
      "PONE",
      "APEX",
      "AXON",
      "EXPO",
      "OXEN",
      "OPEN",
      "NOPE",
      "PANE",
      "NEAP",
      "PEN",
      "PAN",
      "ONE",
      "NAP",
      "AXE",
    ],
  },
  {
    id: 10,
    letters: ["R", "A", "E", "B", "G", "Z"], // Rearranged from "BARGE"
    validWords: [
      "BARGE",
      "GRAZE",
      "GARB",
      "GRAB",
      "BRAG",
      "BEAR",
      "BARE",
      "RAGE",
      "GEAR",
      "AGER",
      "ZEBRA",
      "BRA",
      "RAG",
      "BAG",
      "AGE",
      "BAR",
    ],
  },
  {
    id: 11,
    letters: ["F", "S", "L", "A", "H", "Y"], // Rearranged from "FLASH"
    validWords: [
      "FLASH",
      "FLAY",
      "SLAY",
      "LASH",
      "HALY",
      "SHAY",
      "ASHY",
      "LAYS",
      "FAYS",
      "LAY",
      "FAY",
      "HAS",
      "HAY",
      "ASH",
    ],
  },
  {
    id: 12,
    letters: ["R", "W", "N", "O", "D", "E"], // Rearranged from "DOWER"
    validWords: [
      "DOWER",
      "DRONE",
      "OWNER",
      "WORE",
      "WORD",
      "RODE",
      "NODE",
      "REDO",
      "WEND",
      "ONE",
      "NEW",
      "NOR",
      "ROW",
      "DOE",
      "DEN",
    ],
  },
  {
    id: 13,
    letters: ["H", "I", "C", "K", "T", "E"], // Rearranged from "KETCH"
    validWords: [
      "KETCH",
      "HIKE",
      "ITCH",
      "TICK",
      "HECK",
      "KITE",
      "CHIT",
      "THICK",
      "ETHIC",
      "KIT",
      "HIT",
      "TIE",
      "ICE",
      "THE",
    ],
  },
  {
    id: 14,
    letters: ["U", "B", "M", "P", "L", "Y"], // Rearranged from "PLUMB"
    validWords: [
      "PLUMB",
      "LUMPY",
      "BUMPY",
      "LUMP",
      "BUMP",
      "PLUM",
      "YUM",
      "UMP",
      "PLY",
      "BUY",
      "BUM",
    ],
  },
  {
    id: 15,
    letters: ["A", "G", "S", "V", "R", "E"], // Rearranged from "GRAVE"
    validWords: [
      "GRAVES",
      "RAVES",
      "GEARS",
      "SAVER",
      "VERSA",
      "RAGE",
      "GEAR",
      "VASE",
      "AGE",
      "AVE",
      "EAR",
      "ERA",
    ],
  },
  {
    id: 16,
    letters: ["F", "L", "O", "G", "E", "S"],
    validWords: [
      "LOGS",
      "FLOG",
      "FOGS",
      "LEGS",
      "GOLF",
      "GLOF",
      "FLEGS",
      "SOLE",
      "GELS",
      "LOG",
      "FOG",
      "LEG",
      "ELF",
      "GOS",
      "SOL",
      "FOE",
    ],
  },
  {
    id: 17,
    letters: ["W", "R", "A", "E", "T", "S"],
    validWords: [
      "WATER",
      "WEARS",
      "STRAW",
      "TREWS",
      "EARTH",
      "STARE",
      "WARTS",
      "TEARS",
      "RAWS",
      "WARE",
      "WARS",
      "RATS",
      "ARTS",
      "WEAR",
      "TEAR",
      "RAW",
      "WAR",
      "EAT",
      "SET",
    ],
  },
  {
    id: 18,
    letters: ["C", "L", "U", "O", "T", "E"],
    validWords: [
      "CLOUT",
      "CUT",
      "CUTE",
      "COLE",
      "COLT",
      "CLOT",
      "LOUT",
      "LOT",
      "TOE",
      "OUT",
      "ELT",
      "LET",
      "COT",
      "CEL",
      "COL",
    ],
  },
  {
    id: 19,
    letters: ["L", "A", "M", "P", "E", "S"],
    validWords: [
      "AMPLE",
      "LAMPS",
      "SPEAL",
      "LAMES",
      "MALES",
      "PLASM",
      "SEPAL",
      "MAPS",
      "PALE",
      "MALE",
      "LAM",
      "SAP",
      "MAP",
      "APE",
    ],
  },
  {
    id: 20,
    letters: ["N", "I", "K", "E", "W", "O"],
    validWords: [
      "WOKE",
      "KINE",
      "KNOW",
      "WONK",
      "WINK",
      "KNEW",
      "WEK",
      "ONE",
      "NEW",
      "KIN",
      "WIN",
      "INK",
      "NOW",
      "OWL",
      "NEO",
    ],
  },
  {
    id: 21,
    letters: ["B", "A", "K", "R", "T", "O"],
    validWords: [
      "BARK",
      "BORK",
      "TROK",
      "KART",
      "BAK",
      "TAB",
      "BAT",
      "KOB",
      "ART",
      "OAK",
      "RAT",
      "ARK",
      "TOB",
    ],
  },
  {
    id: 22,
    letters: ["L", "B", "T", "E", "A", "R"], // Rearranged from "TABLE"
    validWords: [
      "TABLE",
      "BLEAT",
      "BLATE",
      "ABLER",
      "ALERT",
      "ALTER",
      "LATER",
      "RABLE",
      "BALE",
      "ABLE",
      "BEAR",
      "TEAR",
      "EAR",
      "BAR",
      "ART",
      "BET",
      "BAT",
    ],
  },
  {
    id: 23,
    letters: ["R", "G", "A", "B", "E", "L"], // Rearranged from "LARGE"
    validWords: [
      "LARGE",
      "REGAL",
      "GLARE",
      "BARGE",
      "BALER",
      "ARGLE",
      "AGER",
      "GEAR",
      "RAGE",
      "BEAR",
      "REAL",
      "BALE",
      "EAR",
      "AGE",
      "BAR",
      "RAG",
    ],
  },
  {
    id: 24,
    letters: ["M", "A", "N", "D", "O", "R"], // Rearranged from "RADON"
    validWords: [
      "RADON",
      "RANDOM",
      "ADORN",
      "DRAMA",
      "DAMON",
      "ANDRO",
      "ROAD",
      "RAND",
      "DRAM",
      "ROAN",
      "NORM",
      "MORN",
      "MAD",
      "MAN",
      "ROD",
      "RAN",
    ],
  },
  {
    id: 25,
    letters: ["S", "N", "I", "K", "G", "E"], // Rearranged from "SINGE"
    validWords: [
      "SINGE",
      "KING",
      "GINS",
      "SIGN",
      "SNIG",
      "GENS",
      "SEG",
      "SING",
      "SKIN",
      "SINE",
      "NISE",
      "GEN",
      "SIN",
      "KIN",
      "ENG",
    ],
  },
  {
    id: 26,
    letters: ["C", "R", "T", "E", "S", "A"], // Rearranged from "CASTER"
    validWords: [
      "CASTER",
      "CRATES",
      "CATERS",
      "REACTS",
      "TRACES",
      "CRESTA",
      "SECT",
      "STARE",
      "TACS",
      "ARCS",
      "STAR",
      "CART",
      "TEAR",
      "EAR",
      "ART",
      "CAR",
    ],
  },
  {
    id: 27,
    letters: ["F", "E", "I", "D", "R", "O"], // Rearranged from "FIRED"
    validWords: [
      "FIRED",
      "FRIED",
      "RIFED",
      "FIREDO",
      "RIDE",
      "DIRE",
      "REDO",
      "RODE",
      "FORE",
      "FORD",
      "FRIED",
      "FED",
      "FIRE",
      "ROD",
      "RIF",
      "DOE",
    ],
  },
  {
    id: 28,
    letters: ["V", "I", "N", "O", "R", "E"], // Rearranged from "RIVEN"
    validWords: [
      "RIVEN",
      "REINV",
      "INVER",
      "VENOR",
      "ROVEN",
      "VIRE",
      "NOVE",
      "RIVE",
      "VEIN",
      "RIVE",
      "NOR",
      "REV",
      "VIE",
      "ORE",
      "ION",
      "VIR",
    ],
  },
  {
    id: 29,
    letters: ["T", "I", "C", "N", "R", "E"], // Rearranged from "CITERN"
    validWords: [
      "CITERN",
      "CRETIN",
      "CRINE",
      "NITRE",
      "INTER",
      "NICER",
      "RECIT",
      "TIER",
      "RENT",
      "CENT",
      "RITE",
      "TINE",
      "TEN",
      "NIT",
      "ICE",
      "NET",
    ],
  },
  {
    id: 30,
    letters: ["M", "E", "B", "R", "A", "K"], // Rearranged from "BREAK"
    validWords: [
      "BREAK",
      "BRAKE",
      "BEAKER",
      "BAKER",
      "MAKER",
      "BARE",
      "RAKE",
      "BEAR",
      "BARK",
      "MARK",
      "EAR",
      "BAR",
      "ARK",
      "ARE",
      "ARM",
    ],
  },
  {
    id: 31,
    letters: ["F", "A", "T", "O", "R", "M"], // Rearranged from "FORMAT"
    validWords: [
      "FORMAT",
      "MORT",
      "FORT",
      "MOAT",
      "TOM",
      "FAT",
      "ROT",
      "RAM",
      "OFT",
      "FRO",
      "ART",
      "MAR",
      "FAR",
      "MAT",
      "RAT",
      "ARM",
    ],
  },
  {
    id: 32,
    letters: ["S", "E", "R", "P", "I", "O"], // Rearranged from "PRIOR"
    validWords: [
      "PRIOR",
      "RISER",
      "SPIER",
      "RISES",
      "REPOS",
      "PERIS",
      "PIER",
      "PISO",
      "POSER",
      "SIER",
      "RIPE",
      "ROPES",
      "ROES",
      "RIP",
      "ROE",
    ],
  },
  {
    id: 33,
    letters: ["B", "I", "N", "O", "D", "E"], // Rearranged from "BIND"
    validWords: [
      "BIND",
      "BIDEN",
      "BONED",
      "BON",
      "BOND",
      "DIN",
      "NOB",
      "DINE",
      "BONE",
      "NODE",
      "BED",
      "NEO",
      "NOD",
      "ONE",
      "DEN",
      "BIN",
    ],
  },
  {
    id: 34,
    letters: ["H", "A", "R", "C", "O", "E"], // Rearranged from "ACHOR"
    validWords: [
      "ACHOR",
      "ORACH",
      "CRASH",
      "CHORA",
      "CHORE",
      "RACHE",
      "ARCH",
      "COACH",
      "CAR",
      "CORE",
      "CARE",
      "RACE",
      "ROE",
      "ARC",
      "OAR",
      "HOE",
    ],
  },
  {
    id: 35,
    letters: ["G", "A", "S", "O", "L", "D"], // Rearranged from "GOLD"
    validWords: [
      "GOLD",
      "GLADS",
      "GLAD",
      "LOADS",
      "SLOG",
      "GOAL",
      "DAG",
      "DOG",
      "SAD",
      "LOG",
      "GAS",
      "SOD",
      "AGO",
      "OLD",
      "LAD",
    ],
  },
  {
    id: 36,
    letters: ["P", "A", "L", "E", "T", "O"], // Rearranged from "PLATE"
    validWords: [
      "PLATE",
      "PALET",
      "PELAT",
      "PATEL",
      "LEAPT",
      "PLEAT",
      "PALE",
      "TALE",
      "TEAL",
      "LATE",
      "PELT",
      "TAPE",
      "PEAT",
      "TAP",
      "APT",
      "LOT",
    ],
  },
  {
    id: 37,
    letters: ["S", "M", "L", "P", "E", "T"], // Rearranged from "STEM"
    validWords: [
      "STEM",
      "PELT",
      "LIMP",
      "MELT",
      "TELS",
      "METS",
      "LAPS",
      "MAPS",
      "TAPE",
      "STEP",
      "LEPT",
      "PLAT",
      "TEPS",
      "LAMP",
      "PAL",
    ],
  },
  {
    id: 38,
    letters: ["K", "O", "R", "S", "N", "I"], // Rearranged from "RISK"
    validWords: [
      "RISK",
      "IRON",
      "SINK",
      "RINS",
      "KINS",
      "ROKS",
      "SONK",
      "INK",
      "KIN",
      "SIR",
      "NOR",
      "SIN",
      "NIS",
      "RIN",
      "INK",
    ],
  },
  {
    id: 39,
    letters: ["M", "I", "A", "S", "O", "N"], // Rearranged from "MAIN"
    validWords: [
      "MAIN",
      "AMINO",
      "MANOS",
      "MASON",
      "MON",
      "AMIN",
      "OSMAN",
      "MINA",
      "AIMS",
      "SON",
      "NOMA",
      "OAS",
      "NIM",
      "SIN",
    ],
  },
  {
    id: 40,
    letters: ["N", "A", "C", "T", "O", "I"], // Rearranged from "ACTION"
    validWords: [
      "ACTION",
      "CATION",
      "ACTIN",
      "CANOT",
      "ANTIC",
      "ATONIC",
      "COAT",
      "COIN",
      "ICON",
      "ACT",
      "NOT",
      "CAT",
      "TIN",
      "OAT",
      "ION",
      "TIC",
    ],
  },
  {
    id: 41,
    letters: ["B", "R", "O", "M", "L", "S"], // Rearranged from "BRIM"
    validWords: [
      "BRIM",
      "MORS",
      "MORB",
      "ROBS",
      "ORBS",
      "SLOB",
      "ROB",
      "RIM",
      "MOR",
      "SIR",
      "ORB",
      "BROS",
      "MOBS",
      "RIB",
      "SOB",
    ],
  },
  {
    id: 42,
    letters: ["G", "I", "L", "O", "T", "E"], // Rearranged from "GELT"
    validWords: [
      "GELT",
      "GILT",
      "GOEL",
      "GLOE",
      "LOG",
      "TOG",
      "LIT",
      "TIE",
      "GET",
      "LOT",
      "LEG",
      "LET",
      "TIG",
      "LEG",
      "GOT",
    ],
  },
];
